export const localities: string[] = [
    'Aguaray',
    'Aguas Blancas',
    'Angastaco',
    'Animaná',
    'Apolinario Saravia',
    'Cachi',
    'Cafayate',
    'Campo Quijano',
    'Campo Santo',
    'Capital',
    'Cerrillos',
    'Chicoana',
    'Colonia Santa Rosa',
    'Coronel Moldes',
    'El Bordo',
    'El Carril',
    'El Galpón',
    'El Jardín',
    'El Potrero',
    'El Quebrachal',
    'El Tala',
    'Embarcación',
    'General Güemes',
    'General Pizzarro',
    'General Mosconi',
    'General Ballivián',
    'Guachipas',
    'Hipólito Yrigoyen',
    'Iruya',
    'Isla de Cañas',
    'Joaquín V. Gonzalez',
    'La Caldera',
    'La Candelaria',
    'La Merced',
    'La Poma',
    'La Viña',
    'Las Lajitas',
    'Los Toldos',
    'Molinos',
    'Nazareno',
    'Otro',
    'Payogasta',
    'Profesor Salvador Mazza',
    'Río Piedras',
    'Rivadavia Banda Norte',
    'Rivadavia Banda Sur',
    'Rosario de la Frontera',
    'Rosario de Lerma',
    'San Antonio de los Cobres',
    'San Carlos',
    'San José de Metán',
    'San Lorenzo',
    'San Ramón de la Nueva Orán',
    'Santa Victoria Este',
    'Santa Victoria Oeste',
    'Seclantás',
    'Tartagal',
    'Tolar Grande',
    'Urundel',
    'Vaqueros',
  ];
  